services:
  postgres:
    image: postgres:17
    container_name: crm-postgres
    environment:
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
      POSTGRES_DB: crm
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: crm-redis
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data

  inbucket:
    image: inbucket/inbucket:latest
    container_name: crm-inbucket
    ports:
      - '9050:9000' # Web UI
      - '2525:2500' # SMTP
      - '1150:1100' # POP3

volumes:
  postgres_data:
  redis_data:
